version: '3'
services:
  server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    env_file: .env
    depends_on:
      - redis
    networks:
      - frontend

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - frontend

networks:
  frontend:
