version: '3'
services:
  server:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - /app/node_modules
      - .:/app
    env_file: .env
    environment:
      REDIS_HOST: redis
      DB_HOST: db
    depends_on:
      - db
      - redis

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME:-checklist}"

  redis:
    image: redis:alpine
    expose:
      - "${REDIS_PORT:-6379}"

volumes:
  db_data:
